# Generated by Django 3.0.3 on 2020-04-20 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_deneme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Deneme',
        ),
    ]
